version: "1.0" 
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WordPressDB
      MYSQL_USER: MyWP_User
      MYSQL_PASSWORD: Pa$$5w0rD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWP_User
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: WordPressDB
    volumes:
      ["./:/var/www/html"]
      
volumes:
  mysql: {}